### PR TITLE
1.0.9 Remove dependency on R2API + Rename folder

### PR DESCRIPTION
**Pull request by kpzip**
I was having some issues getting this to work after the recent RoR2 Update caused by an issue with R2API. I fixed it by not using R2API entirely and by just setting fields w/o reflection. I also cleaned up some code and renamed folders to remove the boilerplate example plugin stuff. also, version bump.

### CODE REVIEW

**Comment by kpzip** [comment]
P.S. I also tested this on the latest version of ror2 and it works fine

**Comment by FelixVolo** [comment]
Thank you for putting effort into it and sorry for the late reply. I'll take a look on it the coming days, merge it and update it on thunderstore. Is there any way to give you credit?

**Comment by kpzip** [comment]
> Thank you for putting effort into it and sorry for the late reply. I'll take a look on it the coming days, merge it and update it on thunderstore. Is there any way to give you credit?

No Problem! Let me know if there are any issues. You don't have to credit me since its only a small change, but if you really want to you can credit me as 'kpzip' and/or link my github page. Thanks!

**Review by FelixVolo — APPROVED** [review]
Thanks very nice and clean code 👍

**Pull request merged**
